Feature store db
hogucc/memo_app pull request #1
Opened 2020-05-14 14:42 UTC by hogucc

2020-05-16 00:12 UTC, komagata commented on memo_app.rb
> +        end
これはresultのままで良いかも？

2020-05-17 09:21 UTC, komagata commented on memo_app.rb
> +      @connection.exec("SELECT title, body FROM Memo where id = $1", [id]) do |result|
resultが元々似た構造なのでわざわざmemoに入れ直す必要ないかも？

2020-05-17 13:31 UTC, hogucc commented on memo_app.rb
> +      @connection.exec("SELECT title, body FROM Memo where id = $1", [id]) do |result|
memoは不要だったので削除しました。
併せて、post "/memos" doで使用していた@memosというインスタンス変数が不要だったので削除しました。

2020-05-18 01:19 UTC, komagata requested changes

2020-05-18 01:19 UTC, komagata commented on memo_app.rb
> +  ensure
`rescue`区のない`ensure`は意味がないはずです〜

2020-05-18 14:49 UTC, hogucc commented on memo_app.rb
> +  ensure
begin~ensureを削除しました。が、begin~ensureの削除ではなくrescueを追加したほうが良かったでしょうか。。@connection.execでエラーが発生した場合、今のコードだと@connection.finishが実行されないように思いました。。

2020-05-19 08:10 UTC, komagata commented on memo_app.rb
> +  ensure
なるほど〜でしたらいいかもです。

rescueの無いensureをみたことなかったので書いちゃいました。

2020-05-19 08:10 UTC, komagata reviewed
確認しました、OKですー🙆‍♂️

2020-05-23 09:16 UTC, merged